name: Deploy to NuxtHub
on: push

jobs:
  deploy:
    name: Deploy to NuxtHub
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      # Uses packageManager from package.json (no version field here)
      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      # If your lockfile is up to date, keep --frozen-lockfile. Otherwise temporarily use --no-frozen-lockfile.
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Ensure NuxtHub module is installed
        run: pnpx nuxthub@latest ensure

      # Create ./dist (nuxt generate -> copy .output/public -> dist)
      - name: Build static dist
        run: pnpm run build:dist

      # Debug: confirm the folder exists
      - name: Show dist
        run: ls -la dist | head -n 50

      - name: Deploy to NuxtHub
        uses: nuxt-hub/action@v2
        with:
          project-key: brandingku-zliy
          # IMPORTANT: use output-directory (not output-dir)
          output-directory: dist
