name: Deploy to NuxtHub
on: push

jobs:
  deploy:
    name: Deploy to NuxtHub
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      # Use pnpm version from package.json:packageManager
      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      # If lockfile can be outdated, temporarily use --no-frozen-lockfile
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Ensure NuxtHub module is installed
        run: pnpx nuxthub@latest ensure

      # Generate static site (produces .output/public)
      - name: Build static
        run: pnpm run generate

      # Debug: confirm the folder exists and has content
      - name: Show .output/public
        run: ls -la .output/public | head -n 50

      - name: Deploy to NuxtHub
        uses: nuxt-hub/action@v2
        with:
          project-key: brandingku-zliy
          output-dir: .output/public
